version: 2

sources:
  - name: sample_project
    database: main # Assuming 'main' is your DuckDB database name as configured in profiles.yml
    schema: main # Assuming 'main' is your DuckDB schema name
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

models:
  - name: stg_customers
    description: "Staging model for customer data."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: "Staging model for order data."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
  - name: stg_products
    description: "Staging model for product data."
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  - name: int_customer_order_summary
    description: "Intermediate model summarizing customer order data."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: total_orders
        tests:
          - not_null
  - name: int_order_product_details
    description: "Intermediate model for detailed order product information."
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
  - name: fct_customer_product_affinity
    description: "Fact model for customer product affinity, showing top products."
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
